group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - right_wheel_joint
     - left_wheel_joint

left_motor_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_joint

right_motor_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'right_wheel_joint'
  right_wheel : 'left_wheel_joint'
  publish_rate: 30               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.005]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.48
  wheel_radius : 0.115

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1

  # Base frame_id
  base_frame_id: base_link #default: base_link

  #custom configuration
  enable_odom_tf: false    #disable transformation

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.55  # m/s
      min_velocity           : -0.55 # m/s
      has_acceleration_limits: false
      max_acceleration       : 500  # m/s^2
      min_acceleration       : -500 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1  # rad/s
      has_acceleration_limits: false
      max_acceleration       : 200  # rad/s^2
